### ISSUE TITLE
not compiling any more

### ISSUE THREAD

**Issue by desie** [GoldenCheetah/GoldenCheetah#2291]
Hi,
Made a git pull this morning and now compilation found en error at:
Cloud/TodaysPlan.cpp:24:25: erreur fatale : QJsonDocument : no such file or directory

result of my last pull:
Fast-forward
 src/Cloud/Dropbox.cpp         |   2 +-
 src/Cloud/FileStore.cpp       |  98 ++++++++---
 src/Cloud/FileStore.h         |   9 ++
 src/Cloud/ShareDialog.cpp     |   4 +-
 src/Cloud/TodaysPlan.cpp      | 366 ++++++++++++++++++++++++++++++++++++++++++
 src/Cloud/TodaysPlan.h        |  77 +++++++++
 src/Core/IntervalItem.cpp     |   4 +-
 src/Core/Settings.h           |   2 +
 src/FileIO/RideFile.cpp       |  23 ++-
 src/FileIO/RideFile.h         |   5 +-
 src/Gui/ConfigDialog.cpp      |   3 +
 src/Gui/ConfigDialog.h        |   1 +
 src/Gui/MainWindow.cpp        |  27 ++++
 src/Gui/MainWindow.h          |   3 +
 src/Gui/Pages.cpp             |  52 ++++--
 src/Gui/Pages.h               |  14 ++
 src/Metrics/RideMetric.h      |   2 +-
 src/Metrics/UserMetric.cpp    |  25 +++
 src/Resources/application.qrc |   1 +
 src/Resources/audio/lap.wav   | Bin 0 -> 66400 bytes
 src/Train/TrainSidebar.cpp    |  18 +++
 src/Train/TrainSidebar.h      |   2 +
 src/src.pro                   |   8 +-
 23 files changed, 700 insertions(+), 46 deletions(-)

any clue ?

**Comment by liversedge** [comment]
Please make sure you are using QT5.

The latest version of QT5 that supports Webkit (a key dependency) is QT5.5.1 

If you want to build with a later release then you will need to add this to your gcconfig.pri
```
DEFINES += NOWEBKIT
```

**Comment by desie** [comment]
I use QT 5.7.1 .
Yesterday compilation was ok, compilation error came with the git pull of this morning. I don't think it's qt version problem, it seems that the line:
#include <QJsonDocument>
in TodaysPlan.cpp is the problem ...

**Comment by liversedge** [comment]
Strange, I build on QT 5.5.1 and it builds fine.

**Comment by amtriathlon** [comment]
It's Ok for me on Ubuntu 16.04 using QT 5.7.1 with NOWEBKIT

**Comment by desie** [comment]
hum sorry, I don't undertstand.
with 5.7.1 qt version, i have to compile with nowebkit  option ?

where is locating QJsonDocument file in your system ?

**Comment by liversedge** [comment]
If you are using the fedora QT 5.7.1 it has webkit compiled in, so you don't need to.
QJsonDocument has been part of QT since 5.0.0.

On OSX the headers are in:
```
Qt551//5.5/clang_64/lib/QtCore.framework/Versions/5/Headers/QJsonDocument
```

I can't check Linux as I am away from my workstation for the week.

**Comment by amtriathlon** [comment]
In my Ubuntu LInux:
/home/ale/Projects/Qt/5.5/gcc_64/include/QtCore/QJsonDocument
/home/ale/Projects/Qt/5.7/gcc_64/include/QtCore/QJsonDocument

**Comment by desie** [comment]
ok, I have found QJsonDocument in /usr/include/qt5/Qtcore/
I have tried the nowebkit defines, same problem.
Gcc don't find QJsonDocument, I will check some system path.

**Comment by liversedge** [comment]
You can ignore nowebkit, its about QT > 5.5 and in your case the QT5 distro has webkit built in (which is not how it usually works).

Sounds like an issue with your toolchain. QJsonDocument typically is installed as a symbolic link to the real file qjsondocument.h

**Comment by desie** [comment]
Last git pull give me a compilation ok.
Is it possible that a git pull give a corrupted or something like that ?

**Comment by liversedge** [comment]
I'm going to close this issue, the problem is your toolchain, not the code.

Sorry.
