### PR TITLE
2nd version with option to choose: logarithmic/linear scale for speed chart, like CS #2647

### PR DESCRIPTION
**Pull request by Walibu**
Added options in to configure "linear" or "logarithmic" scale of the critical speed chart.
According amtriathlon:
"I stand my original position but, if you make the scale log/linear an option for the user, I will be glad to apply the change." see #2647

It was mainly straight forward, after I got used to Qt again.

The minor change for compiling on Ubuntu 16.04 with gcc-5.4.0 or older comes as well, its the c++11 in src.pro

### CODE REVIEW

**Comment by liversedge** [comment]
why is src.pro changed?

**Comment by Walibu** [comment]
I had problems building with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) and QT 5.5.1
I got errors like this:
Cloud/CloudService.h:590:65: error: ‘CloudService::CloudServiceSetting’ is not a class or namespace
                 value = returning->settings.value(CloudService::CloudServiceSetting::DefaultURL, "");
After asking google, I found this:
https://gcc.gnu.org/projects/cxx-status.html

Sorry, you can remove this change src.pro, then a add it in my gcconfig.pri
Right now, I try a full build without this flag, but a week ago a could not build.

**Comment by liversedge** [comment]
You need to build with 5.8 or higher really (GC needs a fair few of the bug fixes), since c++11 support only arrived in QT 5.6 you are way out of date. if you remove the src.pro updates I can merge.

**Comment by Walibu** [comment]
Ok, thank you, does that work with the revert inside the pull request?

So, I have to update Qt in the next days.

**Comment by amtriathlon** [comment]
Can you rebase to consolidate the changes on one commit?

**Comment by Walibu** [comment]
Sorry, how i do that?
I am reading through https://help.github.com/articles/about-git-rebase/
but not sure what to do, what is the purpose, remove the commit with src.pro changes?

**Comment by Walibu** [comment]
With the command:
$ git rebase -i upstream/master

I get the following lines:

pick a3304a3 Use logarithmic scale for speed chart, like CS
pick 35ef4a1 Ubuntu 16.04 or 14.04 with gcc-5.4.0 or older, does not compile, unless c++ 2011 is set
pick dd9ba9b Configurable scale for speed chart like CS, logarithmic or linear
pick c3907de Enable option for configurable time scale on Speed data series only
pick 41c6d77 Refactoring, extract method for updating options checkboxes
pick aa69aa0 Revert src.pro changes

and now?

**Comment by mtbkeith** [comment]
you would do as follows from your command line;

GoldenCheetah # git checkout master
GoldenCheetah # git pull
GoldenCheetah # git checkout Your-Branch-Name
GoldenCheetah # git rebase -i master

# this now gives you a VI editor; which should show your two commits.
something like
pick 99949 38484 your first commit message
pick 94944 29394 your second commit message

change the second "pick" to an "f" for "fixup" (you need to do this in
insert mode by pressing 'i' and moving the cursor around).
exit the vi editor by exiting insert mode by hitting 'esc' and then write
the changes of the file ":wq"
then you do a push to your branch as follows;
GoldenCheetah # git push --force

This essentially does a merge/squash of the two commits. Now your two
commits will be put together as one, and the changes to the "src.pro" file
will not show up for everyone else in master.

Thanks,
Keith

**Comment by mtbkeith** [comment]
Now that I see your output a slight change to my previous directions,
change all picks after the first one to 'f' for fixup. It's just cleaner to
merge/squash them all together.

**Comment by Walibu** [comment]
So I change all "pick" to "f" except the first
Write it out and close the editor.
Hope this works...

**Comment by Walibu** [comment]
Done, but now I can't see the changes and the refactoring as separate commits, should I change that if possible or leave it?

**Comment by mtbkeith** [comment]
Walter,

You can see it in the history of your branch. It often does no one else any
good to see separate commits in "master";

ex:
change1: change log scale of drawing
change2: oops, change variable names
change3: code review changes

those should all be squashed down into one commit.

One thing I didn't mention is if there is a very active project you will
have to resolve conflicts during the rebase operation for the files which
others have changed. For your work, I assumed no one else was changing the
same files (a safe bet that shows to be true).

Keith

**Comment by Walibu** [comment]
Thanks Keith

Lg Walter

**Comment by amtriathlon** [comment]
I added a refresh after Linear scale option change and merged.
Thanks Walter!

**Comment by Walibu** [comment]
Thanks Alejandro!
