### ISSUE TITLE
Mac build failing due to commit 32ab055cab

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#897]
Commit 32ab055cab0b2bc94e9a298233c2018e494c0011 breaks the Mac build.

Error from MainWindow.cpp

```
MainWindow.cpp:786: warning: unused parameter ‘want’
MainWindow.cpp: In member function ‘void MainWindow::configChanged()’:
MainWindow.cpp:1828: error: ‘blackline’ was not declared in this scope
MainWindow.cpp:1833: error: ‘blackline’ was not declared in this scope
MainWindow.cpp:1853: error: a function-definition is not allowed here before ‘{’ token
MainWindow.cpp:1860: error: a function-definition is not allowed here before ‘{’ token
MainWindow.cpp:1948: error: expected `}' at end of input
MainWindow.cpp:786: warning: unused parameter ‘want’
MainWindow.cpp: In member function ‘void MainWindow::configChanged()’:
MainWindow.cpp:1828: error: ‘blackline’ was not declared in this scope
MainWindow.cpp:1833: error: ‘blackline’ was not declared in this scope
MainWindow.cpp:1853: error: a function-definition is not allowed here before ‘{’ token
MainWindow.cpp:1860: error: a function-definition is not allowed here before ‘{’ token
MainWindow.cpp:1948: error: expected `}' at end of input
```
