### ISSUE TITLE
Current git master fails to build with error: cannot convert ‘QString’ to ‘const QFile&’

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4699]
```
Gui/Pages.cpp: In member function ‘bool IconsPage::eventFilterIconList(QEvent*)’:
Gui/Pages.cpp:2756:57: error: cannot convert ‘QString’ to ‘const QFile&’
 2756 |                 if (IconManager::instance().addIconFile(path)) {
      |                                                         ^~~~
      |                                                         |
      |                                                         QString
```

I'm building on gentoo with qt 6.9.1

I think it's related to https://github.com/GoldenCheetah/GoldenCheetah/pull/4695
@thejockl : could you have a look?

**Comment by thejockl** [comment]
@MeisterP can you please test PR #4700 - this works for me both with Qt 6.8.2 and 5.15.15 (both installed from Debian unstable)

**Comment by MeisterP** [comment]
> can you please test PR [#4700](https://github.com/GoldenCheetah/GoldenCheetah/pull/4700)

Yes, this works with Qt 6.9.1 as well. Thanks for the quick fix 👍
