### ISSUE TITLE
Train\VideoWindow.cpp(403): error C2039: 'Duration': is not a member of 'VideoSyncFile'

### ISSUE THREAD

**Issue by paulj49457** [GoldenCheetah/GoldenCheetah#4499]
In the latest build on Qt5.15 & Visual studio

#if defined(GC_VIDEO_QT5)
        // QT doesn't expose media frame rate so make due with duration.
        **_double videoSyncDuration = currentVideoSyncFile->Duration;_**
        if (videoSyncDuration > 0) {
            double mediaDuration = (double)mp->duration();
            if (mediaDuration > 0) {
                videoSyncTimeAdjustFactor = mediaDuration / videoSyncDuration;
            }
        }
#endif

**Comment by paulj49457** [comment]
see #4500 for a fix
