### PR TITLE
SportPlusHelp Cloud Integration

### PR DESCRIPTION
**Pull request by LucaRa177**
Hello, 
I developed a simple integration (based on the already existing ones) so that GC is able to send specific trainings to SportPlusHealth servers to be included into user’s training list.
I hope everything’s fine and you will accept it. 
Best regards, 
Luca

### CODE REVIEW

**Comment by liversedge** [comment]
The integration test failed with "SportPlusHealthUploader.cpp:26:10: fatal error: 'QMessageLogger' file not found"

**Comment by liversedge** [comment]
Currently we build on QT4.8.6 and QT5.5, I think QMessageLogger is QT 5.3 or higher.

**Comment by LucaRa177** [comment]
Sorry, you are right I developed using QT5. Anyway I removed that library, as I needed it just for logging during the development.

**Comment by liversedge** [comment]
Perfect. Will wait for the integration test then check through and merge.
I assume there are no API tokens/secrets needed?

**Comment by liversedge** [comment]
Oh, QJsonDocument is not in QT4.8 either. You are welcome to make the whole thing conditional on QT5. We did that with the recent Dropbox support; we will likely drop support for QT4 in January...

**Comment by LucaRa177** [comment]
I see that in ShareDialog it's been used the MVJSONReader. Is it compatible with QT4? I could fastly switch to this library and commit the changes.

**Comment by liversedge** [comment]
Sure. Its a very simple library that doesn't handle arrays well, but good for small snippets.

**Comment by LucaRa177** [comment]
Everything should be OK. How does it work now? Is there some step I still miss?
Sorry for the questions, but I never took part to a collaborative opensource project until now.
Could you also tell me when these changes will appear in the downloadable release of the app?

**Comment by liversedge** [comment]
Yes it compiles fine. 

I need to check the code through and then merge probably today or tomorrow.
We have not started the release cycle for v3.3 yet, although a first public development build for it was published yesterday. I am sure we will publish a release candidate shortly and this will be in there.

The full release of v3.3 is hoped to be Jan 1st 2016, assuming tests go well.

**Comment by LucaRa177** [comment]
OK thank you for the info ;)

**Comment by liversedge** [comment]
Sorry Luca but if I open the Share Dialog without configuring name/pass the checkbox is enabled and checked !  It should be disabled until the user settings have been made. I looked at the code and it seemed ok, do you know why this happens?

**Comment by LucaRa177** [comment]
Hello, I just checked deleting the credentials already inserted and that checkbox was ok (unchecked and not enabled). But I'm not in the use case "I enter the first time without ever inserting the credentials", as I think you are. Is there a way to "reset" the application (I tried with a "Rebuild all" but it was not enough)?

**Comment by liversedge** [comment]
Lets get it into the repo, we can fix up nits later.
The release candidates are out soon so best not to miss that bus !

**Comment by LucaRa177** [comment]
Great thank you. I saw you edited the method " SportPlusHealthUploader::canUpload", was that missing empty parameter causing our problem?

**Comment by LucaRa177** [comment]
Sorry, I've just read the commit comment, everything's clear now. Thanks for the fix.

**Comment by LucaRa177** [comment]
Hello,
not sure if this is the right place to post about, but I noticed a minor error. On Golden Cheetah website, page "http://www.goldencheetah.org/#section-features", it is written "Sports Plus Health" while we should see "SportPlusHealth" (no "s", and no spaces).
How could we fix this?
Thank you,
Luca

**Comment by liversedge** [comment]
Have fixed it.

**Comment by LucaRa177** [comment]
Thank you
