### ISSUE TITLE
compilation fails with QT < 5.13

### ISSUE THREAD

**Issue by qheath** [GoldenCheetah/GoldenCheetah#3490]
With Qt 5.11, I get
> Charts/ChartBar.cpp: In member function ‘virtual bool ChartBarItem::event(QEvent*)’:
> Charts/ChartBar.cpp:510:17: error: ‘class QPainterPath’ has no member named ‘clear’
>          hotspot.clear();

45a628b4b9c032b36bfbc1a1ae66c4bfca6b6713 added https://github.com/GoldenCheetah/GoldenCheetah/blob/6e8bad3d19c21d53417638eed662ff6321cfe19f/src/Charts/ChartBar.cpp#L510 which, according to https://doc.qt.io/qt-5/qpainterpath.html#clear, was introduced in Qt 5.13.

According to https://github.com/GoldenCheetah/GoldenCheetah/blob/6e8bad3d19c21d53417638eed662ff6321cfe19f/INSTALL-LINUX#L5 the oldest Qt supported is 5.9.

I don't know anything about QPainterPath, so I don't know if this is fixable with a simple `#ifdef` or if we now need 5.13.

**Comment by liversedge** [comment]
Yeah- we build with 5.14.2 now. Avoid 5.15 as it breaks qwt. we're on a bit of a tightrope till qt6 comes out and we start with version bingo all over again...... we will fixup qwt at some point.
