### ISSUE TITLE
error: 'LoadedMedia' was not declared in this scope

### ISSUE THREAD

**Issue by martinkg** [GoldenCheetah/GoldenCheetah#3907]
Hi,

when compiling the tag  commit/d17d3c59a38a97f39060d686bff778a9c405480e
on Fedora 34 i get this error message:
```

Train/VideoWindow.cpp: In member function 'bool VideoWindow::hasActiveVideo() const':
Train/VideoWindow.cpp:225:9: error: 'LoadedMedia' was not declared in this scope
  225 |     if (LoadedMedia == mp->mediaStatus())
      |         ^~~~~~~~~~~
```

How can i fix this ?
The package qt5-qtmultimedia-devel is installed.

Regards

**Comment by amtriathlon** [comment]
This is an error introduced by https://github.com/GoldenCheetah/GoldenCheetah/pull/3764, that line likely needs to be changed to:
```
    if (mp->state() != QMediaPlayer::StoppedState)
```
